### ISSUE TITLE
java.nio.file.FileSystemException: java.net.ConnectException: Connection timed out: connect

### ISSUE THREAD

**Issue by goodale** [robtimus/sftp-fs#8]
I am getting a connection timed out error with the following code.    I've included similar code using Jsch that works without issue.   Not sure if this is an issue with my usage of sftp-fs or something with the library

`
String sftpHost = "sftp://ftp.server.com";
String user = "hello";
String pwd = "world";
char[] cPwd = pwd.toCharArray();
SFTPEnvironment env = new SFTPEnvironment()			        .withUsername(user).withPassword(cPwd).withConfig("StrictHostKeyChecking", "no");
FileSystem fs = FileSystems.newFileSystem(URI.create(sftpHost), env);
Path p = fs.getPath("images");
System.out.println(p.getNameCount());`

Note:  I've tried appending port '22' to the end of the URI but that also fails with timed out error

The following code using straight Jsch (but not creating NIO file system) succeeds:

`String SFTPHOST = "ftp.server.com";
 String SFTPPORT = 22;
 String SFTPUSER = "hello";
String SFTPPASS = "world";
String SFTPBASEDIR = "images";
		try {
			JSch jsch = new JSch();
			session = jsch.getSession(SFTPUSER, SFTPHOST, SFTPPORT);
			session.setPassword(SFTPPASS);
			java.util.Properties config = new java.util.Properties();
			config.put("StrictHostKeyChecking", "no");
			session.setConfig(config);
			session.connect();
			channel = session.openChannel("sftp");
			channel.connect();
			channelSftp = (ChannelSftp) channel;
		} catch (Exception ex) {
			_log.error("error connecting in init " + ex.getMessage(), ex);
			throw ex;
		}`

**Comment by robtimus** [comment]
Could you post the stack trace you're getting? Could you also print `env` and post what it contains? (Of course hide the password etc if it shows up.)

If the contents of `env` is what I think it is, your code using straight JSch should be almost exactly what the file system does. I could find only one difference - the file system calls `channel.pwd()`. Although I doubt that would cause the issue, it's the only difference I could find.

**Comment by goodale** [comment]
sure thing. here is the toString() and stacktrace:

System.out.println(env.toString());
{password=[C@1e67b872, config={StrictHostKeyChecking=no}, username=XXXX}

FileSystem fs = FileSystems.newFileSystem(URI.create("sftp://ftp.cachefly.com:22"), env);

java.nio.file.FileSystemException: Session.connect: java.net.SocketTimeoutException: Read timed out
	at com.github.robtimus.filesystems.sftp.SFTPEnvironment.asFileSystemException(SFTPEnvironment.java:721)
	at com.github.robtimus.filesystems.sftp.SFTPEnvironment.connect(SFTPEnvironment.java:665)
	at com.github.robtimus.filesystems.sftp.SFTPEnvironment.openChannel(SFTPEnvironment.java:568)
	at com.github.robtimus.filesystems.sftp.SSHChannelPool$Channel.<init>(SSHChannelPool.java:241)
	at com.github.robtimus.filesystems.sftp.SSHChannelPool$Channel.<init>(SSHChannelPool.java:229)
	at com.github.robtimus.filesystems.sftp.SSHChannelPool.<init>(SSHChannelPool.java:99)
	at com.github.robtimus.filesystems.sftp.SFTPFileSystem.<init>(SFTPFileSystem.java:107)
	at com.github.robtimus.filesystems.sftp.SFTPFileSystemProvider.newFileSystem(SFTPFileSystemProvider.java:100)
	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:344)
	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:293)
	at com.regattacentral.util.SFTPTestNIO.test(SFTPTestNIO.java:94)
	at com.regattacentral.util.SFTPTestNIO.main(SFTPTestNIO.java:36)
Caused by: com.jcraft.jsch.JSchException: Session.connect: java.net.SocketTimeoutException: Read timed out
	at com.jcraft.jsch.Session.connect(Session.java:565)
	at com.jcraft.jsch.Session.connect(Session.java:183)
	at com.github.robtimus.filesystems.sftp.SFTPEnvironment.connect(SFTPEnvironment.java:660)
	... 10 more

**Comment by robtimus** [comment]
That's really odd. I've debugged the code, and at the point of failure the following statements have been executed:

    JSch jsch = new JSch();
    Session session = jsch.getSession("XXX", "ftp.server.com", 22);
    session.setPassword("XXX");
    session.setConfig(config);
    session.connect();

This last step is the one that fails. It doesn't even reach the `session.openChannel("sftp")` step. The odd thing is that this is exactly what you're executing manually. It's not the file system code that is causing the exception, it's JSch. There are no stricter timeouts or anything.

**Comment by robtimus** [comment]
I've just released a new version with a new JSch replacement (see #11). Perhaps that will solve the issue.

**Comment by goodale** [comment]
I'll give it a try.  Thanks!
